name: Cancel redundant jobs

on:
  push:
    branches:
      - '!master' # always build master
  pull_request:

# workflow ids can be found via
# https://api.github.com/repos/timberio/vector/actions/workflows
#
jobs:
  cancel-tests:
    name: Cancel redundant tests.yml workflows
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        workflow_id: 1463240
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  cancel-benches:
    name: Cancel redundant benches.yml workflows
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        workflow_id: 1481114
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  cancel-lints:
    name: Cancel redundant lints.yml workflows
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        workflow_id: 1463054
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  cancel-e2e:
    name: Cancel redundant e2e.yml workflows
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event_name != 'schedule'
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        workflow_id: 2103337
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
